### ISSUE TITLE
Empty format string is not supported at the end of a file 

### ISSUE THREAD

**Issue by cserezwan** [Marco-Z/Spoofing-Face-Recognition-With-3D-Masks#1]
While running the code it's showing the following error:
Error using dlmread (line 147)
Empty format string is not supported at the end of a file.

Error in csvread (line 48)
    m=dlmread(filename, ',', r, c);

Error in landmarks (line 64)
    data = cat(2,data,csvread(file,1,0));

Error in main (line 53)
            landmarks(false)

Error in run_main (line 30)
main(features_type, test_only, c, gamma);

Have any solution please?
![empty format string](https://user-images.githubusercontent.com/4254488/35769182-06fda45e-0942-11e8-8245-63c63215acfb.jpg)

**Comment by Marco-Z** [comment]
There are probably some errors in the `.csv` files.
Try looking at [this](https://www.mathworks.com/matlabcentral/answers/141530-questions-about-csvread-when-import-data-into-matlab) discussion and see if it helps.

**Comment by cserezwan** [comment]
The CSV file is generated by your code.

Actually nothing in it except the header. So where did it's finding Empty format string at end of a line.
There's no empty line. So I'm not able to delete any line. Can you please share any csv file what you have used.
![image](https://user-images.githubusercontent.com/4254488/35852002-a5312c58-0b64-11e8-81d8-ab53c8c4733e.png)

**Comment by Marco-Z** [comment]
Unfortunately, I can't right now.
Try to look at the `3.Results/a.faces` folder. Are there any files in any of the sub-folders?
The algorithm should have extracted faces for each data sample.
If the files are not there you have some problems with the face recognition (do you have the correct dataset? We used [3DMAD](http://www.idiap.ch/dataset/3dmad)), otherwise, you have problems in the facial features extraction (this is done through `face_land.exe`).
