### ISSUE TITLE
Can you provide the detail steps

### ISSUE THREAD

**Issue by cploveflower** [Marco-Z/Spoofing-Face-Recognition-With-3D-Masks#3]
When I try to run the code, I find it have many errors,Can you provide the detail steps about the datasets prepare and begin,Thank you very much!

**Comment by Marco-Z** [comment]
Hi,
The script reads `hdf5` files. they have to be put in specific folders.
The hierarchy of folders should look like this:

- `1.Dataset`  
    - `3DMAD`  
        - `train` 
            - `real` 
            - `fake` 
        - `dev` 
            - `real` 
            - `fake` 
        - `test` 
            - `real` 
            - `fake` 

The `1.Dataset` folder should be on the same level as the `main.m`.
The `hdf5` files should be put inside the `real` and `fake` folders.
You can split the dataset as you like.
Hope this helps.

If you have any further questions, please attach some error log, so that I can help better.
Thank you!

**Comment by cploveflower** [comment]
Thank you for the answer,but when I run the landmarks,it have the error as follows:
![img_20190104_174411](https://user-images.githubusercontent.com/38428610/50682112-c4fb3d00-1048-11e9-954d-8e38821d5e2a.jpg)
it shows that the'face_land.exe' is not an internal or external command, 
nor a runnable program or batch file,do you know the reason?Thank you!

**Comment by Marco-Z** [comment]
It looks like it cannot find the executable file.
The `face_land.exe` program should be in the same folder as the `landmarks.m` (that is `2.Functions`).
